(window.webpackJsonp=window.webpackJsonp||[]).push([[45],{105:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return i})),n.d(t,"metadata",(function(){return c})),n.d(t,"rightToc",(function(){return s})),n.d(t,"default",(function(){return p}));var r=n(2),a=n(6),o=(n(0),n(161)),i={id:"error-boundaries",title:"Error Boundaries"},c={unversionedId:"error-boundaries",id:"error-boundaries",isDocsHomePage:!1,title:"Error Boundaries",description:"Litho provides a feature for handling errors raised inside Components inspired",source:"@site/docs/error-boundaries.md",slug:"/error-boundaries",permalink:"/docs/error-boundaries",editUrl:"https://github.com/facebook/litho/edit/master/website/docs/error-boundaries.md",version:"current",sidebar:"mainSidebar",previous:{title:"Custom Layout",permalink:"/docs/custom-layout"},next:{title:"OnAttached/OnDetached",permalink:"/docs/onattached-ondetached"}},s=[{value:"Conceptual Overview",id:"conceptual-overview",children:[]},{value:"Providing Fallbacks",id:"providing-fallbacks",children:[]},{value:"Re-raising Exceptions",id:"re-raising-exceptions",children:[]},{value:"Why not Try/Catch?",id:"why-not-trycatch",children:[]},{value:"Limitations",id:"limitations",children:[]}],l={rightToc:s};function p(e){var t=e.components,n=Object(a.a)(e,["components"]);return Object(o.b)("wrapper",Object(r.a)({},l,n,{components:t,mdxType:"MDXLayout"}),Object(o.b)("p",null,"Litho provides a feature for handling errors raised inside Components inspired\nby the eponymous feature in ",Object(o.b)("a",Object(r.a)({parentName:"p"},{href:"https://reactjs.org/docs/error-boundaries.html"}),"React"),".\nIt allows you to catch and handle errors higher up in the tree and provide\nappropriate fallback, logging or retry mechanisms."),Object(o.b)("p",null,"Prefer to jump straight into code? Our ",Object(o.b)("a",Object(r.a)({parentName:"p"},{href:"https://github.com/facebook/litho/tree/master/sample/src/main/java/com/facebook/samples/litho/errors"}),"sample\napp"),"\ncontains a full example of using error boundaries in a Sections-powered list."),Object(o.b)("h2",{id:"conceptual-overview"},"Conceptual Overview"),Object(o.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(o.b)("div",Object(r.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(r.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(r.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(o.b)("path",Object(r.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(o.b)("div",Object(r.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"}," Error boundaries are still considered experimental and disabled by\ndefault. To use them, you have to enable ",Object(o.b)("inlineCode",{parentName:"p"},"ComponentsConfiguration.enableErrorBoundaryComponent"),".\nThe supported delegate methods are currently limited to:"),Object(o.b)("ul",{parentName:"div"},Object(o.b)("li",{parentName:"ul"},Object(o.b)("inlineCode",{parentName:"li"},"onCreateLayout")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("inlineCode",{parentName:"li"},"onCreateLayoutWithSizeSpec")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("inlineCode",{parentName:"li"},"onMount"),"\nWe plan to expand them to more delegates in the future.")))),Object(o.b)("p",null,"A component becomes an error boundary when it defines an\n",Object(o.b)("a",Object(r.a)({parentName:"p"},{href:"pathname:///javadoc/com/facebook/litho/annotations/OnError.html"}),Object(o.b)("inlineCode",{parentName:"a"},"OnError"))," delegate method.\nThe method will receive all exceptions that occur are raised in supported\nmethods of components sitting underneath the error boundary in the tree."),Object(o.b)("pre",null,Object(o.b)("code",Object(r.a)({parentName:"pre"},{className:"language-java"}),'@LayoutSpec\npublic class ErrorBoundarySpec {\n\n  @OnCreateLayout\n  static Component onCreateLayout(ComponentContext c, @Prop Component child) {\n    return child;\n  }\n\n  @OnError\n  static void onError(ComponentContext c, Exception error) {\n    Log.e("ErrorBoundary", "Exception caught at boundary.", error);\n\n    if (safeToIgnore(error)) {\n      return;\n    } else {\n      throw new RuntimeException(error);\n    }\n  }\n}\n')),Object(o.b)("p",null,'This shows an example of an error boundary that wraps a child component\nand swallows errors it regards as "safe" while always sending them to the log first.\nIn case that an exception is deemed unsafe, it is reraised as ',Object(o.b)("inlineCode",{parentName:"p"},"RuntimeException"),"\nand will likely crash the application."),Object(o.b)("p",null,"But let's be very clear: Ignoring errors can be dangerous and if you know the\nexceptions that can be raised inside a method, you should handle them locally."),Object(o.b)("h2",{id:"providing-fallbacks"},"Providing Fallbacks"),Object(o.b)("p",null,"Especially during development and for debug builds, it can be very helpful to\nprovide error information instead of crashing the app for unexpected errors.\nLet's expand the previous example and show an error message in place of the\nwrapped component by using ",Object(o.b)("a",Object(r.a)({parentName:"p"},{href:"/docs/mainconcepts/coordinate-state-actions/hoisting-state"}),"State"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(r.a)({parentName:"pre"},{className:"language-java"}),'@LayoutSpec\npublic class ErrorBoundarySpec {\n\n  @OnCreateLayout\n  static Component onCreateLayout(\n      ComponentContext c,\n      @Prop Component child,\n      @State Optional<Exception> error) {\n\n    if (error.isPresent()) {\n      return Column.create(c)\n          .marginDip(YogaEdge.ALL, 16)\n          .child(\n              Text.create(c)\n                  .text("Error caught at boundary: " + error.get().getMessage())\n                  .textColor(Color.RED)\n                  .build())\n          .build();\n    }\n\n    return child;\n  }\n\n')),Object(o.b)("p",null,"Instead of simply returning the child, we now receive a state value for an\nexception. If it is set, we instead return a Text component that displays\nthe error message."),Object(o.b)("pre",null,Object(o.b)("code",Object(r.a)({parentName:"pre"},{className:"language-java"}),"  @OnCreateInitialState\n  static void createInitialState(\n    ComponentContext c,\n    StateValue<Optional<Exception>> error) {\n\n    error.set(Optional.<Exception>empty());\n  }\n\n  @OnUpdateState\n  static void updateError(\n    StateValue<Optional<Exception>> error,\n    @Param Exception e) {\n\n    error.set(Optional.of(e));\n  }\n")),Object(o.b)("p",null,"We set up a state value for the error object we receive in ",Object(o.b)("inlineCode",{parentName:"p"},"@OnError"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(r.a)({parentName:"pre"},{className:"language-java"}),"  @OnError\n  static void onError(ComponentContext c, Exception error) {\n    ErrorBoundary.updateErrorAsync(c, error);\n  }\n}\n")),Object(o.b)("p",null,"Lastly, when the ",Object(o.b)("inlineCode",{parentName:"p"},"onError")," delegate gets called, we trigger an asynchronous\nstate update to the error. This will in turn rerender the component and run\n",Object(o.b)("inlineCode",{parentName:"p"},"onCreateLayout")," with the error value set."),Object(o.b)("p",null,"Note that we use ",Object(o.b)("inlineCode",{parentName:"p"},"updateErrorAsync")," here as opposed to the synchronous variant.\nThis is important as crashes in MountSpecs can otherwise cause undefined\nbehavior."),Object(o.b)("h2",{id:"re-raising-exceptions"},"Re-raising Exceptions"),Object(o.b)("p",null,"An error boundary may choose to only handle certain classes of errors. For\nexample, you may want to introduce a ",Object(o.b)("inlineCode",{parentName:"p"},"MediaRetryErrorBoundarySpec")," for crashes\nthat arise from your media player and provide a mechanism to restart the\nplayback. You may, however, not want to handle errors that are related to a\ncommenting function."),Object(o.b)("p",null,"You can re-raise an exception from within an ",Object(o.b)("inlineCode",{parentName:"p"},"onError")," delegate so that it\npropagates up the component tree until it is either caught by another error\nboundary or hits the root and causes a crash. This is done by calling\n",Object(o.b)("a",Object(r.a)({parentName:"p"},{href:"pathname:///javadoc/com/facebook/litho/ComponentUtils.html#raise-com.facebook.litho.ComponentContext-java.lang.Exception-"}),Object(o.b)("inlineCode",{parentName:"a"},"ComponentUtils.raise"))," with your context and the exception."),Object(o.b)("pre",null,Object(o.b)("code",Object(r.a)({parentName:"pre"},{className:"language-java"}),"@OnError\nstatic void onError(ComponentContext c, Exception error) {\n  if (canHandle(error)) {\n    ErrorBoundary.updateError(c, error);\n  } else {\n    ComponentUtils.raise(c, error);\n  }\n}\n")),Object(o.b)("h2",{id:"why-not-trycatch"},"Why not Try/Catch?"),Object(o.b)("p",null,"You may wonder why all this additional infrastructure would be necessary when\nyou could just use ",Object(o.b)("inlineCode",{parentName:"p"},"try"),"/",Object(o.b)("inlineCode",{parentName:"p"},"catch"),". It turns out that there is no easily\naccessible place to wrap your user code like this."),Object(o.b)("p",null,"The following example shows how ",Object(o.b)("strong",{parentName:"p"},"not")," to do it:"),Object(o.b)("pre",null,Object(o.b)("code",Object(r.a)({parentName:"pre"},{className:"language-java"}),"@OnCreateLayout\nstatic Component onCreateLayout(ComponentContext c) {\n  // This won't work.\n  try {\n    return PossiblyCrashingSubTitleComponent\n        .create(c)\n        .color(Color.RED)\n        .build();\n  } catch (Exception e) {\n    return FallbackComponent.create(c).exception(e).build();\n  }\n}\n")),Object(o.b)("p",null,"Assuming that ",Object(o.b)("inlineCode",{parentName:"p"},"PossiblyCrashingSubTitleComponentSpec")," throws an exception in\n",Object(o.b)("inlineCode",{parentName:"p"},"onCreateLayout")," this would not be caught by this block. The reason for this is\nthat you are just returning a declaration of your layout here and don't actually\nexecute any code. This is the responsibility of the Litho framework, hence the\nneed to provide higher-level infrastructure to give you access to those errors."),Object(o.b)("h2",{id:"limitations"},"Limitations"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},"Error boundaries are a highly experimental feature. There are many ways in\nwhich errors can happen and there could be cases which we fail to correctly\nrecover from, leaving Litho in an inconsistent state.")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},"Errors thrown in the error boundary itself are not caught but propagated\nfurther up the chain. For instance, if the ",Object(o.b)("inlineCode",{parentName:"p"},"onCreateLayout")," inside your\n",Object(o.b)("inlineCode",{parentName:"p"},"ErrorBoundarySpec")," raises an exception, it won't be passed to the ",Object(o.b)("inlineCode",{parentName:"p"},"onError"),"\nmethod of the same component.")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},"Do not use Error Boundaries for control flow. This should go without saying as\nthis is sitting on top of exceptions which themselves shouldn't be used for\ncontrol flow. Error boundaries exist to deal with the realities of application\ndevelopment and improve user experience, not to structure your applications\naround them.")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},"Not all delegate methods are supported yet. We plan to expand support in the\nfuture, so ensure that your error boundaries can handle exceptions from all\ncomponent code.")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},"Exceptions that happen during state updates or in event handlers are not\nsupported at the moment."))))}p.isMDXComponent=!0},161:function(e,t,n){"use strict";n.d(t,"a",(function(){return u})),n.d(t,"b",(function(){return h}));var r=n(0),a=n.n(r);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function i(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}function c(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?i(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):i(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function s(e,t){if(null==e)return{};var n,r,a=function(e,t){if(null==e)return{};var n,r,a={},o=Object.keys(e);for(r=0;r<o.length;r++)n=o[r],t.indexOf(n)>=0||(a[n]=e[n]);return a}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(r=0;r<o.length;r++)n=o[r],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var l=a.a.createContext({}),p=function(e){var t=a.a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):c(c({},t),e)),n},u=function(e){var t=p(e.components);return a.a.createElement(l.Provider,{value:t},e.children)},d={inlineCode:"code",wrapper:function(e){var t=e.children;return a.a.createElement(a.a.Fragment,{},t)}},b=a.a.forwardRef((function(e,t){var n=e.components,r=e.mdxType,o=e.originalType,i=e.parentName,l=s(e,["components","mdxType","originalType","parentName"]),u=p(n),b=r,h=u["".concat(i,".").concat(b)]||u[b]||d[b]||o;return n?a.a.createElement(h,c(c({ref:t},l),{},{components:n})):a.a.createElement(h,c({ref:t},l))}));function h(e,t){var n=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var o=n.length,i=new Array(o);i[0]=b;var c={};for(var s in t)hasOwnProperty.call(t,s)&&(c[s]=t[s]);c.originalType=e,c.mdxType="string"==typeof e?e:r,i[1]=c;for(var l=2;l<o;l++)i[l]=n[l];return a.a.createElement.apply(null,i)}return a.a.createElement.apply(null,n)}b.displayName="MDXCreateElement"}}]);